spring.application.name=kampay
spring.datasource.url=jdbc:postgresql://localhost:5432/kampay
spring.datasource.username=postgres
spring.datasource.password=422002Kamsi!

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto = update